import javax.swing.JOptionPane;
import static java.lang.System.out;
class SuperstitionsDialog
{
static public void main(String...ar)
 {
  int choice=Integer.parseInt( JOptionPane.showInputDialog("List of top 10 Superstition in India and possible logic behind them\n1.Hanging lemon and 7 green chilies\n2.If a black cat crosses your path, it's a bad omen\n3.Breaking mirror brings bad luck\n4.Twitching of the eye is inauspicious\n5.Removing evil eye Nazar Utaarna\n6.Adding one rupee to a gift sum\n7.Do not sweep after sunset\n8.Don't go near a Peepal tree in the night\n9.Cutting nails on saturday\n10.Do not sleep with your head facing the North\nFor detailed information enter your choice"));
  switch(choice)
   {
 case 1: JOptionPane.showMessageDialog(null,"Hanging lemon and 7 green chilies\nIt is believed in India that 'Alakshmi', the goddess of misfortune can bring bad luck to the shop \n owners or business. Since, she likes sour, pungent and hot things, shop owners in India hang lemon and 7 green \n chilies at their door so that the goddess eat her favourite food, satisfy her hunger and leave without entering the shop.\nFor more information go on link->https://www.youtube.com/watch?v=2A5fNj6dWDo");
           break;
case 2: JOptionPane.showMessageDialog(null,"If a black cat crosses your path, it's a bad omen\nJust because they are black cats? Not just in India but this is a popular belief in the west too. The \n origin of this superstition has come from the Egyptians who believed that black cats were evil creatures and \n they bring bad luck. In India, black colour is generally associated with the Lord Shani. It is said that if a black cat\n crosses your path, then you should let somebody else pass before you do. This way,\n the first person will have all the bad luck and you won't.\nFor more information go on link->https://www.youtube.com/redirect?q=http%3A%2F%2Fbit.ly%2FSubToColeAndMarmalade&redir_token=nqEFR8bQfMgHOlOeCRPwidKLn2V8MTU2ODAxNzEyMEAxNTY3OTMwNzIw&event=video_description&v=i9GQbI5fFTk");
           break;
case 3: JOptionPane.showMessageDialog(null,"Breaking mirror brings bad luck\nIt is said that in earlier times, mirror used to be very expensive but brittle. To avoid the negligence, the ancient people from Rome started preaching that breaking mirrors will bring you 7 years of bad luck. Why 7 years? This is because Romans believe that it takes 7 years for a life to renew itself. So, the image of a person, who does not have a good health, will break the mirror and after 7 years, his life will renew itself and he'll be in good health.");
           out.println("For more information go on link->https://www.youtube.com/watch?v=vr0q43w3G4w");
           break;
case 4: JOptionPane.showMessageDialog(null,"Twitching of the eye is inauspicious\nThe superstition is different in different cultures. It is considered good luck in some cultures\n and bad in some other. It differs according to gender as well. Since it is related to eyes, there are many scientific\n reasons behind the twitching of the eyes. Eye twitching could be due to stress, alcohol, tiredness, allergies, strain or just dry eyes.\nFor more information go on link->https://www.youtube.com/watch?v=QXseRuvJR2A");
           break;
case 5: JOptionPane.showMessageDialog(null,"Removing evil eye (Nazar Utaarna)\nPutting a little dot of kohl on the side of a child's forehead is very common in India. The practice\n is called Nazar Utaarna. It is done to protect the little kid from any evil eyes and \n prevent anyone from putting a negative vibe over the kid. The evil eye can cause severe \n damage to whom it turns. It is said that putting a black spot on a child's forehead \n will make the child look ugly to the evil powers and hence, the kid will stay protected.\nFor more information go on link->https://www.youtube.com/watch?v=P40mRPMdaQI");
           break;
case 6: JOptionPane.showMessageDialog(null,"Adding one rupee to a gift sum\nOn weddings and special occasions, we Indians generally like to gift money and it won't be\n 100 or 1,000 but 101 or 1,001. We add one rupee coin to the entire sum. It is considered a \nblessing, love and luck. But, the main reason to add that extra coin is to make the entire sum an odd number\n and it will be indivisible, it is good for the married couple. If we don't add one rupee coin, the sum will end in a zero \nwhich means 'the end'.\nFor more information go on link->https://www.youtube.com/watch?v=32vnic3UPsE");
           break;
case 7:  JOptionPane.showMessageDialog(null,"Do not sweep after sunset\nGoddess Lakshmi will walk out of your house if you sweep you place after sunset. In a country,\n where we pray to goddess Lakshmi so that she bestows wealth on us, any idea that leads \nto her walking out is considered inauspicious. Why sunset? This is because, it is believed that the goddess generally\n pays a visit after sunset so, if you sweep your place after sunset, she won't come in.\nFor more information go on link->https://www.youtube.com/watch?v=pLReZ5TEvP0");
           break;
case 8: JOptionPane.showMessageDialog(null,"Don't go near a Peepal tree in the night\nPeepal is one tree the ghosts like to hover around and if you sleep around a peepal tree at night,\n the ghosts will kill you. Do you know that plants and living beings keep a balance in nature.\n In the morning, when the photosynthesis is occurring in them, they absorb carbon dioxide, change it into energy\n and give out oxygen in the air which we breathe in but in the night, the opposite reaction occurs.\n At night, plants exhale carbon dioxide while there is lack of sunlight. Animals sleep under trees all the time,\n why don't we see all of them dead, next morning?\nFor more information go on link->https://www.youtube.com/watch?v=K6_L7JOYz7U");
           break;
case 9:  JOptionPane.showMessageDialog(null,"Cutting nails on saturday\nHindus believe that it’s inauspicious to cut hair and nails on Saturday because it angers planet Saturn (Shani),\n which then brings bad luck. Moreover, one must not cut one’s nails after sunset. The origin of this belief\n could be that in sweeping away the cut nails in the darkness, one could inadvertently sweep away small valuables because of \npoor visibility (Not sweeping after dark is also a superstition in India) One almost funny \nsuperstition associated with washing hair is that a student must never wash his/her\n hair before an exam. Doing so will ensure that everything the student has learned will\n be washed away.\nFor more information go on link->https://www.youtube.com/watch?v=KeCKIwQ97q8");
           break;
case 10: JOptionPane.showMessageDialog(null,"Do not sleep with your head facing the North\nOur ancestors probably knew about the relation between Earth's magnetic field and the human\n body's field ( biomagnetism ).  They probably made this rule of sleeping with your head in the South because \n of the harmful effects related to blood pressure and other diseases that asymmetry \n with the Earth's magnetic field would create. However, today we only get to hear that 'sleeping with one's head \n in the north is inviting death' not why.\nFor more information go on link->https://www.youtube.com/watch?v=AW1ca9_NOuA");
           break;
default: JOptionPane.showMessageDialog(null,"Invalid choice");
            break; 
    }
 }
}